disabled = false
locale = "en"
label = "English"
weight = 1
title = "Gwendal Beaumont"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  description = "My personal website"
  copyright = "&copy; { year }"

[params.author]
  name = "Gwendal Beaumont"
  email = "contact@gwendalbeaumont.fr"
  image = "img/author.jpg"
  imageQuality = 95
  headline = "PhD student in computer sciences"
  links = [
    { email = "mailto:contact@gwendalbeaumont.fr" },
    { github = "https://github.com/GwendalBeaumont" },
    { google-scholar = "https://scholar.google.com/citations?user=-PaQiHgAAAAJ" },
    { linkedin = "https://linkedin.com/in/gwendalbeaumont" },
    { orcid = "https://orcid.org/0000-0001-9861-4008" },
    { researchgate = "https://www.researchgate.net/profile/Gwendal-Beaumont" },
  ]
